// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Rust code generator for compiled structures.
//!
//! Following rules are applied for generation.
//!
//! Namespaces:
//!  - Each namespace is generated in each own module
//!  - Camel case identifieds in namespaces are converted to snake case.
//!  - If namespace more than one ids then submodules are generated in according to namespace.
//!

/// Escaped identifier construction
pub mod ident;

/// Mod name
pub mod mod_name;

/// Documentation generation
pub mod doc;

/// Configuration of generation
pub mod config;

/// Short type name (only name)
pub mod type_name;

/// Full type name (name with fully qualified path)
pub mod full_type_name;

/// Property name for structs
pub mod property_name;

/// Action name for structs
pub mod action_name;

/// Mod definition
pub mod mod_def;

/// Struct definition
pub mod struct_def;

/// Types definitions
pub mod type_def;

/// Enum definitions
pub mod enum_def;

/// Generation helpers for properties in create and update request structures.
pub mod serializable_properties;

use crate::compiler::Compiled;
use crate::compiler::ForcedUpdate;
use crate::compiler::IsCreatable;
use crate::compiler::QualifiedName;
use proc_macro2::TokenStream;
use quote::quote;
use std::fmt::Display;
use std::fmt::Formatter;
use std::fmt::Result as FmtResult;

#[doc(inline)]
pub use action_name::ActionFullTypeName;
#[doc(inline)]
pub use action_name::ActionName;
#[doc(inline)]
pub use config::Config;
#[doc(inline)]
pub use enum_def::EnumDef;
#[doc(inline)]
pub use full_type_name::FullTypeName;
#[doc(inline)]
pub use mod_def::ModDef;
#[doc(inline)]
pub use mod_name::ModName;
#[doc(inline)]
pub use property_name::StructFieldName;
#[doc(inline)]
pub use serializable_properties::SerializableProperties;
#[doc(inline)]
pub use struct_def::StructDef;
#[doc(inline)]
pub use type_def::TypeDef;
#[doc(inline)]
pub use type_name::TypeName;

/// Errors that can occur during code generation.
pub enum Error<'a> {
    BaseTypeConflict,
    NameConflict,
    CreateStruct(TypeName<'a>, Box<Self>),
    CreateSimplType(QualifiedName<'a>, Box<Self>),
}

impl Display for Error<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match self {
            Self::BaseTypeConflict => write!(
                f,
                "derivation property name conflict, see `base_type_prop_name` configuration parameter"
            ),
            Self::NameConflict => write!(f, "name conflict"),
            Self::CreateStruct(id, err) => write!(f, "while create struct {id}\n{err}"),
            Self::CreateSimplType(id, err) => write!(f, "while create simple type {id}\n{err}"),
        }
    }
}

pub struct RustGenerator<'a> {
    root: ModDef<'a>,
    config: Config,
}

impl<'a> RustGenerator<'a> {
    /// # Errors
    ///
    /// Returns error if Rust code cannot be generated by the compiled
    /// data structure.
    pub fn new(compiled: Compiled<'a>, config: Config) -> Result<Self, Error<'a>> {
        let forced_updates = compiled.forced_updates();

        let root = ModDef::default();
        let mut cactions = compiled.actions;
        let creatable = compiled.creatable_entity_types;
        let mut excerpt_copies = compiled.excerpt_copies;
        let root = cactions.iter().try_fold(root, |m, (_, ma)| {
            ma.iter()
                .try_fold(m, |m, (_, a)| m.add_action_type(a, &config))
        })?;
        let root = compiled
            .complex_types
            .into_iter()
            .try_fold(root, |m, (name, t)| {
                let actions = cactions.remove(&name).unwrap_or_default();
                let forced = ForcedUpdate::new(forced_updates.contains(&name));
                m.add_complex_type(t, actions, forced, &config)
            })?;
        let root = compiled
            .entity_types
            .into_iter()
            .try_fold(root, |m, (_, t)| {
                let is_creatable = IsCreatable::new(creatable.contains(&t.name));
                let forced = ForcedUpdate::new(forced_updates.contains(&t.name));
                let type_excerpt_copies = excerpt_copies
                    .remove(&t.name)
                    .map(|v| v.into_iter().collect::<Vec<_>>())
                    .unwrap_or_default();
                m.add_entity_type(t, is_creatable, type_excerpt_copies, forced, &config)
            })?;
        let root = compiled
            .type_definitions
            .into_iter()
            .try_fold(root, |m, (_, t)| m.add_type_definition(t))?;
        let root = compiled
            .enum_types
            .into_iter()
            .try_fold(root, |m, (_, t)| m.add_enum_type(t))?;
        Ok(Self { root, config })
    }

    /// Generate Rust code from the collected data.
    #[must_use]
    pub fn generate(self) -> TokenStream {
        let mut tokens = TokenStream::new();
        tokens.extend(quote! {
            /// This code is automatically generated by CSDL generator. DO NOT EDIT!
            const _CSDL_GENERATED_CODE_COMMENT: &str = "";

            #[allow(unused_imports)]
            use nv_redfish_core::{
                EntityTypeRef,
                Expandable,
                Updatable,
                Deletable,
                Creatable,
                RedfishSettings,
                Bmc,
                ActionError,
                Reference,
                NavProperty,
                Action,
                ODataId,
                ODataETag,
                ReferenceLeaf,
                AdditionalProperties,
                DynamicProperties,
                ToSnakeCase,
                de_optional_nullable,
                de_required_nullable,
            };

            pub mod edm {
                //! This module is hardcoded in compiler. If you want
                //! to change it you need to change source code of
                //! generator.
                //!
                /// Mapping of `Edm.Boolean` type
                pub type Boolean = bool;
                /// Mapping of `Edm.DateTimeOffset` type
                pub type DateTimeOffset = nv_redfish_core::EdmDateTimeOffset;
                /// Mapping of `Edm.Decimal`
                pub type Decimal = f64;
                /// Mapping of `Edm.Double` type
                pub type Double = f64;
                /// Mapping of `Edm.Duration` type
                pub type Duration = nv_redfish_core::EdmDuration;
                /// Mapping of `Guid` type
                pub type Guid = nv_redfish_core::EdmGuid;
                /// Mapping of `Edm.Int64` type
                pub type Int64 = i64;
                /// Mapping of `Edm.String` type
                pub type String = ::std::string::String;
                /// Mapping of `Edm.PrimitiveType` type
                pub type PrimitiveType = nv_redfish_core::EdmPrimitiveType;
            }
        });
        self.root.generate(&mut tokens, &self.config);
        tokens
    }
}

#[cfg(test)]
mod tests {
    use super::Config;
    use super::RustGenerator;
    use crate::compiler::ActionFilter;
    use crate::compiler::Config as CompilerConfig;
    use crate::compiler::SchemaBundle;
    use crate::edmx::Edmx;
    use crate::optimizer::optimize;
    use crate::optimizer::Config as OptimizerConfig;
    use quote::quote;

    #[test]
    fn read_model_serialization_is_selected_per_generator_invocation() -> Result<(), String> {
        let schema = r#"<edmx:Edmx Version="4.0">
          <edmx:DataServices>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Example">
              <EntityType Name="Example"/>
            </Schema>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Resource">
              <EntityType Name="Resource" Abstract="true"/>
              <EntityType Name="ResourceCollection" Abstract="true"/>
            </Schema>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Settings">
              <ComplexType Name="Settings"/><ComplexType Name="PreferredApplyTime"/>
            </Schema>
          </edmx:DataServices>
        </edmx:Edmx>"#;

        let bundle = SchemaBundle::new(
            vec![Edmx::parse(schema).map_err(|error| error.to_string())?],
            Vec::new(),
        );

        let serialize_and_deserialize = quote! {
            #[derive(Serialize)]
            #[derive(Deserialize, Debug)]
            pub struct Example
        }
        .to_string();

        for enabled in [false, true] {
            let compiled = bundle
                .compile_all(CompilerConfig::default())
                .map_err(|error| error.to_string())?;

            let config = Config {
                serialize_read_models: enabled,
                ..Config::default()
            };
            let generated = RustGenerator::new(compiled, config)
                .map_err(|error| error.to_string())?
                .generate()
                .to_string();

            assert_eq!(generated.contains(&serialize_and_deserialize), enabled);
        }

        Ok(())
    }

    #[test]
    fn root_oem_action_bound_to_resolve_only_type_respects_filter() -> Result<(), String> {
        let oem_schema = r#"<edmx:Edmx Version="4.0">
          <edmx:DataServices>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="NvidiaChassis">
              <Action Name="Reset" IsBound="true">
                <Parameter Name="Chassis" Type="Chassis.v1_0_0.OemActions"/>
                <Parameter Name="ResetType" Type="NvidiaChassis.v1_0_0.NvidiaChassisResetType" Nullable="false"/>
              </Action>
              <Action Name="AuxPowerReset" IsBound="true">
                <Parameter Name="Chassis" Type="Chassis.v1_0_0.OemActions"/>
                <Parameter Name="Mode" Type="Edm.String"/>
              </Action>
            </Schema>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="OtherOem">
              <Action Name="Ignored" IsBound="true">
                <Parameter Name="Chassis" Type="Chassis.v1_0_0.OemActions"/>
              </Action>
            </Schema>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="NvidiaChassis.v1_0_0">
              <EnumType Name="NvidiaChassisResetType">
                <Member Name="ForceDpuReset"/>
              </EnumType>
            </Schema>
          </edmx:DataServices>
        </edmx:Edmx>"#;
        let resolve_schema = r#"<edmx:Edmx Version="4.0">
          <edmx:DataServices>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Chassis.v1_0_0">
              <ComplexType Name="OemActions"/>
            </Schema>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="ResolveOnly">
              <ComplexType Name="OemActions"/>
              <Action Name="Ignored" IsBound="true">
                <Parameter Name="ResolveOnly" Type="ResolveOnly.OemActions"/>
              </Action>
            </Schema>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Resource">
              <EntityType Name="Resource" Abstract="true"/>
              <EntityType Name="ResourceCollection" Abstract="true"/>
            </Schema>
            <Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="Settings">
              <ComplexType Name="Settings"/>
              <ComplexType Name="PreferredApplyTime"/>
            </Schema>
          </edmx:DataServices>
        </edmx:Edmx>"#;

        let bundle = SchemaBundle::new(
            vec![Edmx::parse(oem_schema).map_err(|error| error.to_string())?],
            vec![Edmx::parse(resolve_schema).map_err(|error| error.to_string())?],
        );

        let compiled_without_action_patterns = bundle
            .compile_all(CompilerConfig {
                action_filter: ActionFilter::new_restrictive(Vec::new()),
                ..CompilerConfig::default()
            })
            .map_err(|error| error.to_string())?;
        let compiled_without_action_patterns = optimize(
            compiled_without_action_patterns,
            &OptimizerConfig::default(),
        );
        let generated_without_action_patterns =
            RustGenerator::new(compiled_without_action_patterns, Config::default())
                .map_err(|error| error.to_string())?
                .generate()
                .to_string();

        assert!(!generated_without_action_patterns.contains("ChassisResetAction"));
        assert!(!generated_without_action_patterns.contains("ChassisAuxPowerResetAction"));
        assert!(!generated_without_action_patterns.contains("pub struct OemActions"));

        let compiled = bundle
            .compile_all(CompilerConfig {
                action_filter: ActionFilter::new_restrictive(vec!["NvidiaChassis.*"
                    .parse()
                    .map_err(|error| format!("{error:?}"))?]),
                ..CompilerConfig::default()
            })
            .map_err(|error| error.to_string())?;
        let action = |name| {
            compiled
                .actions
                .values()
                .flat_map(|actions| actions.values())
                .find(|action| action.name.inner().inner() == name)
                .unwrap_or_else(|| panic!("{} action is compiled", name))
        };
        assert!(action("Reset").parameters[0].required.into_inner());
        assert!(!action("AuxPowerReset").parameters[0].required.into_inner());
        let compiled = optimize(compiled, &OptimizerConfig::default());
        let generated = RustGenerator::new(compiled, Config::default())
            .map_err(|error| error.to_string())?
            .generate()
            .to_string();
        let reset_action = generated
            .split_once("pub struct ChassisResetAction")
            .map(|(_, rest)| rest)
            .and_then(|rest| rest.split_once('}').map(|(body, _)| body))
            .expect("the OEM action request type is generated");
        let oem_actions = generated
            .split_once("pub struct OemActions")
            .map(|(_, rest)| rest)
            .and_then(|rest| rest.split_once('}').map(|(body, _)| body))
            .expect("the action binding type is generated");

        assert!(generated.contains("pub enum NvidiaChassisResetType"));
        assert!(generated.contains("pub struct ChassisAuxPowerResetAction"));
        assert!(reset_action.contains("pub reset_type"));
        assert!(reset_action.contains("NvidiaChassisResetType"));
        assert!(!reset_action.contains("Option"));
        assert!(oem_actions.contains("pub reset"));
        assert!(oem_actions.contains("pub aux_power_reset"));
        assert!(generated.contains("pub async fn reset"));
        assert!(generated.contains("pub async fn aux_power_reset"));
        assert!(!generated.contains("ChassisIgnoredAction"));
        assert!(!generated.contains("ResolveOnlyIgnoredAction"));

        Ok(())
    }
}
