// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use nv_redfish_core::Bmc;
use serde_json::Error as JsonError;
use std::error::Error as StdError;
use std::fmt::Debug;
use std::fmt::Display;
use std::fmt::Formatter;
use std::fmt::Result as FmtResult;

/// Redfish Errors.
pub enum Error<B: Bmc> {
    /// Errors generated by BMC access.
    Bmc(B::Error),
    /// Account service is not supported by the BMC.
    #[cfg(feature = "accounts")]
    AccountServiceNotSupported,
    /// No available account slot found. This error happens for
    /// `slot_defined_user_accounts` feature.
    #[cfg(feature = "accounts")]
    AccountSlotNotAvailable,
    /// JSON parse error.
    Json(JsonError),
}

impl<B: Bmc> Display for Error<B> {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        match self {
            Self::Bmc(err) => write!(f, "BMC error: {err}"),
            Self::Json(err) => write!(f, "JSON error: {err}"),
            #[cfg(feature = "accounts")]
            Self::AccountServiceNotSupported => {
                write!(f, "Account service is not supported by system")
            }
            #[cfg(feature = "accounts")]
            Self::AccountSlotNotAvailable => {
                write!(f, "Free account slot is not found")
            }
        }
    }
}

impl<B: Bmc> Debug for Error<B> {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        Display::fmt(self, f)
    }
}

impl<B: Bmc> StdError for Error<B> {}
