// SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Redfish protocol client
//!
//! This crate provides a thin, ergonomic layer on top of generated Redfish
//! schema types and the `nv-redfish-core` primitives. It focuses on:
//! - High-level entry points (for example, [`ServiceRoot`])
//! - Modular, feature-gated services (enable only what you need)
//! - OEM extension support (also under feature flags)
//! - Patch helpers for vendor quirks that deviate from the Redfish CSDL
//!
//! Relationship to other crates
//! - Depends on `nv-redfish-core` for transport-agnostic traits (`Bmc`) and
//!   foundational types (`ODataId`, navigation properties, actions).
//! - Uses code generated by the CSDL compiler (included via the internal
//!   `schema` module) and re-exports ergonomic wrappers where applicable.
//! - The set of compiled schemas is controlled by `features.toml` to include
//!   only what is required by enabled features — keeping the build as
//!   lightweight as possible.
//!
//! Features
//! - `accounts`: enables the `AccountService` wrappers (implemented).
//! - `events`: enables the Events service wrappers (planned).
//! - OEM-specific feature flags (planned) enable vendor extensions when needed.
//!
//! Status
//! - Currently, the `accounts` service is implemented. More services and OEM
//!   extensions will be added to support a variety of vendors in a compatible
//!   manner.
//!

#![deny(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::suspicious,
    clippy::complexity,
    clippy::perf
)]
#![deny(
    clippy::absolute_paths,
    clippy::todo,
    clippy::unimplemented,
    clippy::tests_outside_test_module,
    clippy::panic,
    clippy::unwrap_used,
    clippy::unwrap_in_result,
    clippy::unused_trait_names,
    clippy::print_stdout,
    clippy::print_stderr
)]
#![deny(missing_docs)]

#[cfg(feature = "accounts")]
pub(crate) mod patch_support;
pub(crate) mod schema;

/// Lenovo OEM support.
#[cfg(feature = "lenovo")]
pub(crate) mod schema_oem_lenovo;

/// Errors defined by the crate.
pub mod error;
/// Supported vendors.
pub mod vendor;

/// Service Root implementation.
pub mod service_root;

/// Accounts Service.
#[cfg(feature = "accounts")]
pub mod accounts;
/// Events Service.
#[cfg(feature = "events")]
pub mod events;

#[doc(inline)]
pub use error::Error;
#[doc(inline)]
pub use service_root::ServiceRoot;
#[doc(inline)]
pub use vendor::Vendor;
