name: CI

on:
  push:
    branches:
      - main
      - "pull-request/[0-9]+"
      - "release/v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.90.0"
      - run: make ci
